routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Middleware\OnlyAdmin;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\HotelController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/home',[HomeController::class,'index'])->name('site.home');
Route::get('/all-package',[PackageController::class,'all_package']);
Route::get('/single-package/{id}',[HomeController::class,'single'])->name('site.single');

Route::get('/all-hotel',[HotelController::class,'all_hotel']);
Route::get('/single-hotel/{id}',[HotelController::class,'single']);

Route::get('/all-blog',[BlogController::class,'all_blog']);
Route::get('/single-blog/{id}',[BlogController::class,'single']);

Route::prefix('/admin')->middleware(['auth',OnlyAdmin::class/*,'verified'*/])->group(function(){
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
    Route::resource('/categories',CategoryController::class);
    Route::resource('/packages',PackageController::class);
    Route::resource('/hotels',HotelController::class);
    Route::resource('/rooms',RoomController::class);
    Route::resource('/blogs',BlogController::class);
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function packages()
    {
        return $this->belongsToMany(Package::class);
    }

    public function blogs()
    {
        return $this->belongsToMany(Blog::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category=Category::get();
        $data['category_list']=$category;
        return view('admin.category.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category=new Category();
        $category->name=$request->name;
        $category->save();
        flash('Successfully created')->success();
        return redirect('/admin/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::find($id);
        if(!$category)
        {
            return redirect('/admin/categories');
        }
        $data["category"]=$category;
        return view('admin.category.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $category=Category::find($id);
        if(!$category)
        {
            return redirect('/admin/categories');
        }
        $category->name=$request->name;
        $category->save();
        return redirect('/admin/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->packages()->detach();
        $data=Category::find($id);
        if(!$data)
        {
            flash('no data found')->error();
            return redirect('/admin/categories');
        }else{
            $data->delete();
            flash('Successfully deleted')->success();
            return redirect()->back();
        }
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Category</h3>
    </div>
    <div class="card-body">
        <form action="{{ route('categories.store') }}" method="POST">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input type="text" class="form-control" name="name" id="category" value="{{ old('name') }}" placeholder="Enter Category Name">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
    </div>
  </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Category</h3>
    </div>
    <div class="card-body">
        <form action="{{ url("/admin/categories/$category->id") }}" method="POST">
            @method("put")
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input type="text" class="form-control" name="name" id="category" value="{{ $category->name }}" placeholder="Enter Category Name">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </form>
    </div>
  </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Category List</h3>
        <div class="card-tools">
          <a  class="btn btn-success" href="{{ url('/admin/categories/create') }}">Add New Category</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered ">
            <thead>
              <tr>
                <th>Name</th>
                <th class="col-3">Action</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($category_list as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td class="col-3">
                      <div class="btn-group" role="group">
                        <a href="{{ url("admin/categories/$item->id/edit") }}" class="btn btn-primary btn-sm">Update</a>
                        {{-- <a href="" class="btn btn-danger btn-sm">Delete</a> --}}
        
                        <form action="{{ url("/admin/categories/$item->id") }}" method="POST" onsubmit="return confirm('Do you really want to delete this category?');">
                            @csrf
                            @method('delete')
                            <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-1">
                        </form>
                      </div>
                    </td>
                  </tr>
                @endforeach 
            </tbody>
          </table>
    </div>
    
  </div>
@endsection