routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Middleware\OnlyAdmin;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\HotelController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/home',[HomeController::class,'index'])->name('site.home');
Route::get('/all-package',[PackageController::class,'all_package']);
Route::get('/single-package/{id}',[HomeController::class,'single'])->name('site.single');

Route::get('/all-hotel',[HotelController::class,'all_hotel']);
Route::get('/single-hotel/{id}',[HotelController::class,'single']);

Route::get('/all-blog',[BlogController::class,'all_blog']);
Route::get('/single-blog/{id}',[BlogController::class,'single']);

Route::prefix('/admin')->middleware(['auth',OnlyAdmin::class/*,'verified'*/])->group(function(){
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
    Route::resource('/categories',CategoryController::class);
    Route::resource('/packages',PackageController::class);
    Route::resource('/hotels',HotelController::class);
    Route::resource('/rooms',RoomController::class);
    Route::resource('/blogs',BlogController::class);
});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function blog__images()
    {
        return $this->hasMany(Blog_Image::class);
    }

}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use Carbon\Carbon;
use App\Models\Blog;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Blog_Image;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blog=Blog::get();
        $data['blog_list']=$blog;
        return view('admin.blog.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category=Category::get();
        $data['categories']=$category;
        return view('admin.blog.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            
            $blog=new Blog();
            $blog->title=$request->title;
            $blog->publishing_date=Carbon::now();
            $blog->author= Auth::user()->name;
            $blog->description=$request->description;
            if($request->hasFile('featured_image')){
                $path = $request->file('featured_image')->store('blog_images','public');
            }
            else{
                $path= null;
            }
            $blog->featured_image=$path;
            $blog->save();
            $blog->categories()->attach($request->categories);
            if($request->hasFile('images')){
                foreach ($request->file('images') as $image) {
                    $path = $image->store('blog_images','public');
                    $image=new Blog_Image();
                    $image->path=$path;
                    $image->blog_id=$blog->id;
                    $image->save();             
                }
            }
            
            flash('Successfully Created')->success();
            return redirect('/admin/blogs');
        }
         catch (\Throwable $th) {
            flash('Something went worng'.$th->getMessage())->error();
        }
    }
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function all_blog()
    {
        $blog=Blog::get();
        $data['blogs']=$blog;
        return view('site.layouts.all_blog',$data);
    }

    public function single($id)
    {
        $blog=Blog::find($id);
        $data['single_blog']=$blog;

        $blog1=Blog::get();
        $data['blogs']=$blog1;
        return view('site.layouts.single_blog',$data);
    }
}

resources/views/admin/blog/create.blade.php
@extends('admin.layouts.app')

@section('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Blog</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Blog</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Blog</h3>
    </div>
    <div class="card-body">
        <form action="{{ route('blogs.store') }}" method="POST" enctype="multipart/form-data" id="form">
            @csrf
            <div class="card-body">

              <div class="form-group">
                <label for="cars">Select package category:</label>
                    <select  name="categories[]" class="form-group categories col-4"  multiple="multiple">
                      @foreach ($categories as $item)
                      <option value="{{ $item->id }}">{{ $item->name }}</option>
                      @endforeach
                    </select>
              </div>

              <div class="form-group">
                <label for="exampleInputEmail1">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ old('title') }}" placeholder="Enter blog title">
              </div>
              @error('title')
                 <p class="text-danger">{{ $message }}</p>
              @enderror

              {{-- <div class="form-group">
                <label for="exampleInputEmail1">Location</label>
                <input type="date" class="form-control" name="publishing_date" id="publishing_date" value="{{ old('publishing_date') }}" placeholder="Enter publish date">
              </div>
              @error('publishing_date')
                 <p class="text-danger">{{ $message }}</p>
              @enderror --}}

              <div class="form-group">
                <label for="exampleInputEmail1">Description</label>
                <textarea name="description" id="" cols="150" rows="10"></textarea>
              </div>
              @error('description')
                 <p class="text-danger">{{ $message }}</p>
              @enderror

              <div class="form-group">
                <label for="exampleInputEmail1">Featured Image</label>
                <input type="file" name="featured_image">
              </div>

              <div class="form-group">
                <label for="exampleInputEmail1">Images</label>
                <input type="file" name="images[]" multiple>
              </div>

            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
    </div>
  </div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $(document).ready(function() {
    $('.categories').select2();
});
</script>
@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Package List</h3>
        <div class="card-tools">
          <a  class="btn btn-success" href="{{ url('/admin/blogs/create') }}">Add New Blog</a>
        </div>
    </div>
    <div class="card-body">
       <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Title</th>
            <th>Publish Date</th>
            <th>Author</th>
            <th>Description</th>
            <th>Featured_Image</th>
            <th>Images</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($blog_list as $blog)
            <tr>
                <td>
                  @foreach ( $blog->categories  as $item)
                      <p>{{ $item->name }}</p>
                  @endforeach
                </td>
                <td>{{ $blog->title }}</td>
                <td>{{ $blog->publishing_date }}</td>
                <td>{{ $blog->author }}</td>
                <td class="mt-5" style="width:100%; height: 300px;display: block; overflow:scroll">{{ $blog->description }}</td>
                
                
                <td><img src="{{ asset("storage/$blog->featured_image") }}" width="100px"></td>
                <td>
                  @foreach ($blog->blog__images as $item)
                  <img src="{{ asset("storage/$item->path") }}" width="100px">
                  @endforeach
                </td>
                <td>
                  <div class="btn-group" role="group">
                    <a href="{{ url("admin/blogs/$blog->id/edit") }}" class="btn btn-primary btn-sm">Update</a>
                   
    
                    <form action="{{ url("/admin/blogs/$blog->id") }}" method="POST" onsubmit="return confirm('Do you really want to delete this category?');">
                        @csrf
                        @method('delete')
                        <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-1">
                    </form>
                  </div>
                </td>
              </tr>
            @endforeach 
        </tbody>
      </table> 
    </div>
    
  </div>
@endsection