routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Middleware\OnlyAdmin;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\HotelController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/home',[HomeController::class,'index'])->name('site.home');
Route::get('/all-package',[PackageController::class,'all_package']);
Route::get('/single-package/{id}',[HomeController::class,'single'])->name('site.single');

Route::get('/all-hotel',[HotelController::class,'all_hotel']);
Route::get('/single-hotel/{id}',[HotelController::class,'single']);

Route::get('/all-blog',[BlogController::class,'all_blog']);
Route::get('/single-blog/{id}',[BlogController::class,'single']);

Route::prefix('/admin')->middleware(['auth',OnlyAdmin::class/*,'verified'*/])->group(function(){
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
    Route::resource('/categories',CategoryController::class);
    Route::resource('/packages',PackageController::class);
    Route::resource('/hotels',HotelController::class);
    Route::resource('/rooms',RoomController::class);
    Route::resource('/blogs',BlogController::class);
});

require __DIR__.'/auth.php';

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;

    public function hotel()
    {
        return $this->belongsTo(Hotel::class);
    }
}

app/Http/Controllers/Admin/RoomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Room;
use App\Models\Hotel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $room=Room::get();
        $data['rooms']=$room;
        return view('admin.room.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hotel=Hotel::get();
        $data['hotel']=$hotel;
        return view('admin.room.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try {
            $room=New Room();
            $room->title=$request->title;
            $room->bed=$request->bed;
            $room->bed_type=$request->bed_type;
            $room->sleep=$request->sleep;
            $room->price_per_night=$request->price_per_night;
            $room->sleep=$request->sleep;
            $room->hotel_id=$request->hotel_id;
    
            if($request->hasFile('room_image')){
                $path = $request->file('room_image')->store('room_images','public');
            }
            else{
                $path= null;
            }
            $room->room_image=$path;
            $room->save();
            flash('Successfully Created')->success();
            return redirect('/admin/rooms');
        } catch (\Throwable $th) {
            flash('Something went worng'.$th->getMessage())->error();

        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $room=Room::find($id);
        $data['hotel']=Hotel::get();
        $data['room']=$room;
        return view('admin.room.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $room=Room::find($id);
        if(!$room)
        {
            return false;
        }
            $room->title=$request->title;
            $room->bed=$request->bed;
            $room->bed_type=$request->bed_type;
            $room->sleep=$request->sleep;
            $room->price_per_night=$request->price_per_night;
            $room->sleep=$request->sleep;
            $room->hotel_id=$request->hotel_id;
    
            if($request->hasFile('room_image')){
                $destination ='storage/'.$room->room_image;
                if(File::exists($destination))
                {
                    File::delete($destination);
                }
                $path = $request->file('room_image')->store('room_images','public');
                $room->room_image=$path;
            }
            $room->save();
            flash('Successfully updated')->success();
            return redirect('/admin/rooms');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        
        $room=Room::find($id);
        if(!$room)
        {
            flash('no data found')->error();
            return redirect('/admin/rooms');
        }else{
            $room->delete();
            flash('Successfully deleted')->success();
            return redirect()->back();
        }
    }

    
}

resources/views/admin/room/create.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Room</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Room</h3>
    </div>
    <div class="card-body">
        <form action="{{ route('rooms.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">

                <div class="form-group">
                    <label for="cars">Select hotel:</label>
                        <select  name="hotel_id" class="form-group categories col-4">
                          @foreach ($hotel as $item)
                          <option value="{{ $item->id }}">{{ $item->title }}</option>
                          @endforeach
                        </select>
                  </div>


              <div class="form-group">
                <label for="exampleInputEmail1">Title</label>
                <input type="text" class="form-control" name="title" value="{{ old('title') }}" placeholder="Enter Room title">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
              @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Bed No</label>
                    <input type="number" class="form-control" name="bed" value="{{ old('bed') }}" placeholder="Enter Bed Number">
                </div>
                  @error('bed')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="cars">Bed Type</label>
                    <select name="bed_type" class="form-select col-2" aria-label="Default select example" value="{{ old('bed_type') }}">
                                <option value="">Select a Option</option>
                                <option value="single">Single</option>
                                <option value="double">Double</option>
                    </select>
                </div>
                  @error('bed_type')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Sleep Person</label>
                    <input type="number" class="form-control" name="sleep" value="{{ old('bed') }}" placeholder="Enter Bed Number">
                </div>
                  @error('bed')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Price Per Night</label>
                    <input type="text" class="form-control" name="price_per_night" value="{{ old('price_per_night') }}" placeholder="Enter price per night">
                </div>
                @error('name')
                 <p class="text-danger">{{ $message }}</p>
                @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Image</label>
                    <input type="file" name="room_image">
                </div>
                  @error('room_image')
                     <p class="text-danger">{{ $message }}</p>
                  @enderror
     

            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
    </div>
  </div>
@endsection

resources/views/admin/room/edit.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Room</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Room</h3>
    </div>
    <div class="card-body">
        <form action="{{ url("admin/rooms/$room->id") }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">

                <div class="form-group">
                    <label for="cars">Select hotel:</label>
                        <select  name="hotel_id" class="form-group categories col-4">
                          @foreach ($hotel as $item)
                          <option value="{{ $item->id }}" {{ $room->hotel_id == $item->id ? 'selected':''}}>{{ $item->title }}</option>
                          @endforeach
                        </select>
                  </div>


              <div class="form-group">
                <label for="exampleInputEmail1">Title</label>
                <input type="text" class="form-control" name="title" value="{{ $room->title }}" placeholder="Enter Room title">
              </div>
              @error('title')
              <p class="text-danger">{{ $message }}</p>
              @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Bed No</label>
                    <input type="number" class="form-control" name="bed" value="{{ $room->bed }}" placeholder="Enter Bed Number">
                </div>
                  @error('bed')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="cars">Bed Type</label>
                    <select name="bed_type" class="form-select col-2" aria-label="Default select example">
                                <option value="">Select a Option</option>
                                <option value="single" {{ $room->bed_type=="single" ? 'selected' : '' }}>Single</option>
                                <option value="double" {{ $room->bed_type=="double" ? 'selected' : '' }}>Double</option>
                    </select>
                </div>
                  @error('bed_type')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Sleep Person</label>
                    <input type="number" class="form-control" name="sleep" value="{{ $room->sleep }}" placeholder="Enter Bed Number">
                </div>
                  @error('bed')
                  <p class="text-danger">{{ $message }}</p>
                  @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Price Per Night</label>
                    <input type="text" class="form-control" name="price_per_night" value="{{ $room->price_per_night }}" placeholder="Enter price per night">
                </div>
                @error('name')
                 <p class="text-danger">{{ $message }}</p>
                @enderror

                <div class="form-group">
                    <label for="exampleInputEmail1">Image</label>
                    <input type="file" name="room_image">
                    <td><img src="{{ asset("storage/$room->room_image") }}" width="100px"></td>
                </div>
                  @error('room_image')
                     <p class="text-danger">{{ $message }}</p>
                  @enderror
     

            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
    </div>
  </div>
@endsection

resources/views/admin/room/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Room List</h3>
        <div class="card-tools">
          <a  class="btn btn-success" href="{{ url('/admin/rooms/create') }}">Add New Room</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered ">
            <thead>
              <tr>
                <th>Hotel name</th>
                <th>Name</th>
                <th>Bed No</th>
                <th>Bed Type</th>
                <th>Sleeping Person</th>
                <th>Price Per Night</th>
                <th>Image</th>
                <th class="col-3">Action</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($rooms as $room)
                <tr>
                  <td>{{ $room->hotel->title }}</td>
                    <td>{{ $room->title }}</td>
                    <td>{{ $room->bed }}</td>
                    <td>{{ $room->bed_type }}</td>
                    <td>{{ $room->sleep }}</td>
                    <td>{{ $room->price_per_night }}</td>
                    <td><img src="{{ asset("storage/$room->room_image") }}" width="100px"></td>
                    <td class="col-3">
                      <div class="btn-group" role="group">
                        <a href="{{ url("admin/rooms/$room->id/edit") }}" class="btn btn-primary btn-sm">Update</a>
                        
        
                        <form action="{{ url("/admin/rooms/$room->id") }}" method="POST" onsubmit="return confirm('Do you really want to delete this room?');">
                            @csrf
                            @method('delete')
                            <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-1">
                        </form>
                      </div>
                    </td>
                  </tr>
                @endforeach  
            </tbody>
          </table>
    </div>
    
  </div>
@endsection